### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by d4nm0** [xNasuni/artlist-downloader#10]
hello,
the script doesn't work when I click on the download button it asks me to log in or pay.
i use orange monkey

**Comment by xNasuni** [comment]
did you install it properly? are the download buttons turning green(music) or pink(sfx)?

this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

**Comment by d31220207** [comment]
> hello, the script doesn't work when I click on the download button it asks me to log in or pay. i use orange monkey

works great with Tampermonkey

![image](https://github.com/user-attachments/assets/ffd8e583-41bb-4d65-bb21-8b329c3c118d)

**Comment by d31220207** [comment]
> did you install it properly? are the download buttons turning green(music) or pink(sfx)?
> 
> this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

I have a suggestion for the future script:

- uppbeat
- premiumbeat
- storyblocks
- app.soundstripe.com
- d31220207.github.io/SFX

**will be awesome**

**Comment by d31220207** [comment]
> did you install it properly? are the download buttons turning green(music) or pink(sfx)?
> 
> this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

doesn't work as well with Tampermonkey

![image](https://github.com/user-attachments/assets/1e5dc8bd-f4d8-492f-a070-76eacccc9594)

**Comment by d31220207** [comment]
> did you install it properly? are the download buttons turning green(music) or pink(sfx)?
> 
> this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

this script does not work for this url

https://artlist.io/sfx/search
https://artlist.io/sfx/pack/
https://artlist.io/sfx/artist/

**Comment by d31220207** [comment]
> did you install it properly? are the download buttons turning green(music) or pink(sfx)?
> 
> this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

Hi, @xNasuni, this script does not work for this url:

- [ ] https://artlist.io/sfx/search
- [ ] https://artlist.io/sfx/pack/
- [ ] https://artlist.io/sfx/artist/
- [ ] https://artlist.io/royalty-free-music/artist
- [ ] https://artlist.io/royalty-free-music/album

**Comment by d31220207** [comment]
> did you install it properly? are the download buttons turning green(music) or pink(sfx)?
> 
> this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

Hi, @xNasuni, this script does not work for this url:

- https://artlist.io/sfx/search
- https://artlist.io/sfx/pack/
- https://artlist.io/sfx/artist/
- https://artlist.io/royalty-free-music/artist
- https://artlist.io/royalty-free-music/album

**Comment by d31220207** [comment]
> did you install it properly? are the download buttons turning green(music) or pink(sfx)?
> 
> this script is only for the music & sound effects part of artlist, if you're trying to use it on other ones like footage then that might be why

Hi @xNasuni 
Can you add an auto download feature for all files. For example all packs, all artists or one album.

**Comment by d4nm0** [comment]
i use for sfx

**Comment by xNasuni** [comment]
i'm aware of this issue now, fix should be coming soon (maybe tonight or tuesday) with support for i think almost every page

**Comment by d4nm0** [comment]
ok i wait your fix. Thx :)

**Comment by xNasuni** [comment]
this issue isn't entirely fixed; please see my latest message in #11 for what i mean
