### ISSUE TITLE
the script doesn't work smtimes

### ISSUE THREAD

**Issue by DB011** [xNasuni/artlist-downloader#7]
![image](https://github.com/xNasuni/artlist-downloader/assets/51798746/e85f75e5-5cab-4fcf-b456-1bec95097f59)

Here is sm buttons not responding to the script at all and when you click download it tells me to subscribe
and the green buttons is working fine

**Comment by andrepartida** [comment]
How to install the script?

**Comment by xNasuni** [comment]
fixed in 3f6753b11919858a3c19a45be93aadf0af32ab5d
