### ISSUE TITLE
xNasuni ig i have the solution

### ISSUE THREAD

**Issue by DB011** [xNasuni/artlist-downloader#8]
okay now im trying to catch all the buttons on sfx page since u make the selectors static im trying to make the code more dynamic to catch all buttons for every request.. im workin on it when i finish i'll upload it to u

**ik you have a life when u get online just text me on discord that's my username : itsdrvgon**

Waiting for u...

**Comment by xNasuni** [comment]
fixed in 3f6753b11919858a3c19a45be93aadf0af32ab5d
